version: '3.3'

networks:
  elk-network:
    external: true

services:
  curator:
    image: elk-demo-curator:latest
    networks:
    - elk-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
      restart_policy:
        condition: any
        delay: 30s
